//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbAgent.Tester.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbAgent.Tester.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User=SYSDBA;
        ///Password=masterkey;
        ///Database=C:\DataBases\TempDB.FDB;
        ///DataSource=localhost;
        ///Port=3050;
        ///Dialect=3;
        ///Charset=NONE;
        ///Role=;
        ///Connection lifetime=15;
        ///Pooling=true;
        ///MinPoolSize=0;
        ///MaxPoolSize=50;
        ///Packet Size=8192;
        ///ServerType=0;.
        /// </summary>
        internal static string MainDb_ConnectionString_SQL {
            get {
                return ResourceManager.GetString("MainDb_ConnectionString_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER TRIGGER PE_TRIGGER_DELETE FOR PROCESS_EVENTS
        ///ACTIVE AFTER DELETE POSITION 0
        ///AS
        /// DECLARE S VARCHAR(3000);
        ///BEGIN
        ///
        ///
        ///    S = &apos;INSERT INTO PROCESS_EVENTS_ACTIONS (
        ///    ID, DONE, CATEGORY_ID, OBJECT_ID, SOUND_OFF_TIME, ELECTRICIAN, GZ_ID, ARRIVE_TIME, DESCRIPTION, DONE_TIMESTAMP,
        ///    SOUND_OFF, ELECTRICIAN_ON, GZ_ON, ARRIVE_ON, REASON_ON, GZ_TIME, DESC_ON, USER_ID, WUSER_NAME, HOST_NAME, REASON_ID, GOBJECT_ID, DEPARTURE_GZ, IS_DELETE_ACTION
        ///) values (:V1, :V2, :V3, :V4, :V5, :V6, :V7, :V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Process_Events_Delete_Trigger_SQL {
            get {
                return ResourceManager.GetString("Process_Events_Delete_Trigger_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PROCESS_EVENTS (DONE, CATEGORY_ID, OBJECT_ID, SOUND_OFF_TIME, ELECTRICIAN, GZ_ID, ARRIVE_TIME, DONE_TIMESTAMP, SOUND_OFF, ELECTRICIAN_ON, GZ_ON, ARRIVE_ON, REASON_ON, GZ_TIME, DESC_ON, USER_ID, WUSER_NAME, HOST_NAME, REASON_ID, GOBJECT_ID, DEPARTURE_GZ)
        ///                    VALUES (0, 4, 70066, NULL, NULL, 0, NULL, NULL, 0, 0, 0, 0, 0, NULL, 0, 0, NULL, NULL, 0, NULL, 0);.
        /// </summary>
        internal static string Process_Events_Insert_Random_SQL {
            get {
                return ResourceManager.GetString("Process_Events_Insert_Random_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER TRIGGER PE_RIGGER_INSERT FOR PROCESS_EVENTS
        ///ACTIVE AFTER INSERT POSITION 0
        ///AS
        /// DECLARE S VARCHAR(3000);
        ///BEGIN
        ///
        ///
        ///    S = &apos;INSERT INTO PROCESS_EVENTS_ACTIONS (
        ///    ID, DONE, CATEGORY_ID, OBJECT_ID, SOUND_OFF_TIME, ELECTRICIAN, GZ_ID, ARRIVE_TIME, DESCRIPTION, DONE_TIMESTAMP,
        ///    SOUND_OFF, ELECTRICIAN_ON, GZ_ON, ARRIVE_ON, REASON_ON, GZ_TIME, DESC_ON, USER_ID, WUSER_NAME, HOST_NAME, REASON_ID, GOBJECT_ID, DEPARTURE_GZ, IS_INSERT_ACTION
        ///) values (:V1, :V2, :V3, :V4, :V5, :V6, :V7, :V8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Process_Events_Insert_Trigger_SQL {
            get {
                return ResourceManager.GetString("Process_Events_Insert_Trigger_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR ALTER TRIGGER PE_TRIGGER_UPDATE FOR PROCESS_EVENTS
        ///ACTIVE AFTER UPDATE POSITION 0
        ///AS
        /// DECLARE S VARCHAR(3000);
        ///BEGIN
        ///
        ///
        ///    S = &apos;INSERT INTO PROCESS_EVENTS_ACTIONS (
        ///    ID, DONE, CATEGORY_ID, OBJECT_ID, SOUND_OFF_TIME, ELECTRICIAN, GZ_ID, ARRIVE_TIME, DESCRIPTION, DONE_TIMESTAMP,
        ///    SOUND_OFF, ELECTRICIAN_ON, GZ_ON, ARRIVE_ON, REASON_ON, GZ_TIME, DESC_ON, USER_ID, WUSER_NAME, HOST_NAME, REASON_ID, GOBJECT_ID, DEPARTURE_GZ, IS_UPDATE_ACTION
        ///) values (:V1, :V2, :V3, :V4, :V5, :V6, :V7, :V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Process_Events_Update_Trigger_SQL {
            get {
                return ResourceManager.GetString("Process_Events_Update_Trigger_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User=SYSDBA;
        ///Password=masterkey;
        ///Database=C:\DataBases\TempDB.FDB;
        ///DataSource=localhost;
        ///Port=3050;
        ///Dialect=3;
        ///Charset=NONE;
        ///Role=;
        ///Connection lifetime=15;
        ///Pooling=true;
        ///MinPoolSize=0;
        ///MaxPoolSize=50;
        ///Packet Size=8192;
        ///ServerType=0;.
        /// </summary>
        internal static string TempDb_ConnectionString_SQL {
            get {
                return ResourceManager.GetString("TempDb_ConnectionString_SQL", resourceCulture);
            }
        }
    }
}
